- console/data/docs/02-configuration.md
- inlet/core/config.go
- inlet/core/hydrate.go
This new setting allows to ignore source and destination autonomous system numbers received from flow data and rely solely on MaxMind's data.
This is useful when an exporter only gets a partial routing table as well a default route from a transit provider. Without it all flows matched against the default route on the exporter have the transit provider's AS number instead of the origin's.
However, as I am not familiar with Akvorado's code, it might not be the best way to implements this and it might be interesting to have this setting available per exporter rather than globally.
> Implements a new configuration setting to ignore ASNs received from flow data

- console/query.go
Using InIfBoundary and/or OutIfBoundary as dimensions yields the following error:
```
{"level":"error","error":"code: 386, message: There is no supertype for types Enum8('undefined' = 0, 'external' = 1, 'internal' = 2), String because some of them are String/FixedString and some of them are not: While processing if(InIfBoundary IN (rows AS _subquery300), [InIfBoundary], ['Other']) AS dimensions","time":"2022-07-16T08:40:34Z","caller":"akvorado/console/graph.go:139","module":"akvorado/console","message":"unable to query database"}
```
This change converts Enum numeric values to their string representation to allow the use of InIfBoundary and/or OutIfBoundary as dimensions.
> Convert InIfBoundary/OutIfBoundary from Enum8 to String to use as a dimension

- console/data/docs/03-usage.md
- console/data/docs/99-changelog.md
- console/filter/parser.peg
- console/filter/parser_test.go
- console/frontend/src/codemirror/lang-filter/syntax.grammar
This does not work for ExporterAddress due to a potential bug in
Clickhouse's isIPAddressInRange when using a LowCardinality type. See
https://github.com/ClickHouse/ClickHouse/issues/39599.
> console: add `<<`/`!<<` operator to subnet match for SrcAddr/DstAddr

- common/helpers/norace.go
- common/helpers/race.go
- console/data/docs/99-changelog.md
- inlet/bmp/config.go
- inlet/bmp/events.go
- inlet/bmp/metrics.go
- inlet/bmp/remove.go
- inlet/bmp/rib.go
- inlet/bmp/rib_test.go
- inlet/bmp/root.go
- inlet/bmp/root_test.go
When the RIB is locked for too long, inlet is hung. Try to ensure give a bit of time for the inlet to move forward between two flush of the RIB. There are various knobs not documnted yet until we get better defaults:
- `inlet.bmp.peer-removal-max-time`: how long to keep the lock
- `inlet.bmp.peer-removal-sleep-interval`: how long to sleep between two runs if we were unable to flush the whole peer
- `inlet.bmp.peer-removal-max-queue`: maximum number of flush requests
- `inlet.bmp.peer-removal-min-routes`: minimum number of routes to flush before yielding
May fix #253
> inlet/bmp: avoid long lock times when flushing peers

- Makefile
This PR adds an additional "all_js" target to the makefile. The default behavior should not change.
**Why is this necessary?**
In certain build environments, it is easier to have a build container only for go, and a build container only for node/js-related tasks. With the all task split up, it is possible to do a multi-stage build, first building the js parts in a node-container, while later building the remaining parts in a go container.
> makefile: Split all target in js and go parts

- console/data/docs/01-install.md
I tried to build the code using `make` with node `v14.16.0` but I got the following error:
```
failed to load config from /home/rnavarro/workspace/akvorado/console/frontend/vite.config.ts
error during build:
Error: Cannot find module 'node:path'
```
A little research showed:
`node:` protocol support for CJS was added only in v16.
After updating to v16+ running `make` succeeded
This PR updates the docs to reflect that.
> Update build docs to reflect necessary NodeJS version

- common/schema/definition.go
- common/schema/root.go
- common/schema/types.go
- console/filter/helpers.go
- console/filter/parser.peg
- console/filter/parser_test.go
This PR adds some improvements to materialized dimensions, especially prefixes:
- it saves the Src/DstNetPrefix as LowCardinality, as we have a high repeatability here
- a flag indicates if a column was materialized
- the filters can be adjusted to use a more performant direct query in case of materialized columns, which is done for prefixes
- tests for the "fast" materialized prefix query are added
> feat: add option for materialized types & improve filter performance for materialized prefixes

- inlet/flow/input/udp/root.go
- inlet/flow/input/udp/root_test.go
This PR adds a metric counting the number of flows sent by the UDP input into the internal processing queue.
With the help of this metric, it is possible to determine the current size of the internal processing queue when debugging delays/dropped flows:
```
akvorado_inlet_flow_input_udp_decoded_flows_total - akvorado_inlet_core_received_flows_total
```
> feat: add decoded flows/queue ingest metric for inlet/udp

- console/data/docs/02-configuration.md
- orchestrator/clickhouse/config.go
- orchestrator/clickhouse/migrations_helpers.go
This PR allows to configure the Kafka group name used by ClickHouse to consume messages from topic. Default value is left as the previous "clickhouse".
This is mandatory for Kafka brokers that enforce syntax validation on group names, with for example provider-specific prefixes.
> orchestrator/clickhouse: Add kafka consumers group name as config parameter

- inlet/kafka/metrics.go
This metric is indeed in milliseconds, so the naming was confusing, even though the description was correct.
> Rename kafka_broker_request_latency_seconds to kafka_broker_request_latency_ms

- console/data/docs/02-configuration.md
- orchestrator/kafka/config.go
- orchestrator/kafka/config_test.go
- orchestrator/kafka/functional_test.go
- orchestrator/kafka/root.go
This PR allows orchestrator to alter Kafka topic configuration only if config has changed, instead of every time except a creation.
This is mandatory for Kafka brokers that does not allow specific config entries alter, and is a good optimization when provider sets some config entries not managed by Akvorado, to avoid unnecessary alters.
> orchestrator/kafka: alter topic configuration only when needed (config diff)

- common/helpers/subnetmap.go
- common/helpers/subnetmap_test.go
- common/remotedatasourcefetcher/config.go
- common/remotedatasourcefetcher/config_test.go
- common/remotedatasourcefetcher/metrics.go
- common/remotedatasourcefetcher/root.go
- common/remotedatasourcefetcher/root_test.go
- common/remotedatasourcefetcher/tests.go
- console/data/docs/02-configuration.md
- inlet/metadata/provider/static/config.go
- inlet/metadata/provider/static/config_test.go
- inlet/metadata/provider/static/root.go
- inlet/metadata/provider/static/root_test.go
- inlet/metadata/provider/static/source.go
- inlet/metadata/provider/static/source_test.go
- orchestrator/clickhouse/config.go
- orchestrator/clickhouse/config_test.go
- orchestrator/clickhouse/http.go
- orchestrator/clickhouse/metrics.go
- orchestrator/clickhouse/root.go
- orchestrator/clickhouse/source.go
- orchestrator/clickhouse/source_test.go
- orchestrator/clickhouse/tests.go
This PR aims to allows static exporters metadata refresh from remote HTTP source in addition of config based metadata.
The feature is greatly inspired from network-sources in orchestrator/clickhouse, so the PR is organized in 2 steps:
* Refactor all generic features from orchestrator/clickhouse/source (for network-sources) in a common component named remotedatasourcefetcher.
* Allow inlet/metadata/static to configure exporter-sources from HTTP endpoints, using the common/remotedatasourcefetcher component.
> inlet/metadata/static: allow exporters configuration refresh from http remote data source

- common/remotedatasourcefetcher/root_test.go
- common/schema/definition.go
- inlet/core/classifier.go
- inlet/core/classifier_test.go
- inlet/core/enricher.go
- inlet/core/enricher_test.go
- inlet/metadata/cache.go
- inlet/metadata/cache_test.go
- inlet/metadata/provider/root.go
- inlet/metadata/provider/snmp/poller.go
- inlet/metadata/provider/snmp/poller_test.go
- inlet/metadata/provider/static/config.go
- inlet/metadata/provider/static/config_test.go
- inlet/metadata/provider/static/root.go
- inlet/metadata/provider/static/root_test.go
- inlet/metadata/provider/static/source.go
- inlet/metadata/provider/static/source_test.go
- inlet/metadata/root.go
- inlet/metadata/root_test.go
- inlet/metadata/tests.go
Sometime exporter name and interface description do not carry all the required information for classification and metadata extraction, supporting a way to provide the data through metadata compoenent (only static seems to make sense at this points) enables more use-cases.
> Support providing exporter and iface metadata through metadata instead of classifiers

- Makefile
- common/remotedatasourcefetcher/root.go
- orchestrator/clickhouse/http.go
- orchestrator/clickhouse/migrations.go
This is enabled by default once we switch to Go 1.22 (in go.mod). See https://tip.golang.org/wiki/LoopvarExperiment
> build: enable loopvar experiment

- cmd/inlet.go
- cmd/testdata/configurations/gnmi/expected.yaml
- cmd/testdata/configurations/gnmi/in.yaml
- cmd/testdata/configurations/snmp-communities-migration/expected.yaml
- cmd/testdata/configurations/snmp-ports/expected.yaml
- cmd/testdata/configurations/snmp-to-metadata/expected.yaml
- console/data/docs/02-configuration.md
- console/data/docs/99-changelog.md
- inlet/metadata/config.go
- inlet/metadata/provider/root.go
- inlet/metadata/provider/static/root.go
- inlet/metadata/root.go
- inlet/metadata/root_test.go
- inlet/metadata/tests.go
This does not work as expected as they are queried asynchronously and the negative cache from a provider can erase the answer from another one.
Would have fixed #1111.
> inlet/metadata: allow definition of multiple providers

- console/clickhouse.go
- console/clickhouse_test.go
- console/root.go
- console/tests.go
This PR aims to expose as an API route, the internal logic to compute the appropriate `table` and `interval` (in seconds) to use.
This is very useful for third party apps like Grafana dashboards, running Akvorado-like SQL queries, to adapt perfectly with current Akvorado configuration.
> console/clickhouse: Expose API route to get best table and interval from time range

- demoexporter/flows/nfdata_test.go
- inlet/flow/config.go
- inlet/flow/config_test.go
- inlet/flow/decoder/config.go
- inlet/flow/decoder/netflow/decode.go
- inlet/flow/decoder/netflow/root.go
- inlet/flow/decoder/netflow/root_test.go
- inlet/flow/decoder/root.go
- inlet/flow/decoder/sflow/root.go
- inlet/flow/decoder/sflow/root_test.go
- inlet/flow/decoder_test.go
- inlet/flow/root.go
Today the timestamp can only be from kernel timetstamp put on the UDP packet by the kernel.
I propose to add 2 alternative methods of getting the timestamp for netflow/IPFix packets:
- TimestampSourceNetflowPacket: use the timestamp field in the netflow packet itself
- TimestampSourceNetflowFirstSwitched: use the FirstSwitched field from each flow (the field is actually in uptime, so we need to shift it according to sysUptime)
Using those fields requires the router to have accurate time (probably NTP), but it allows for architectures where a UDP packet is not immediately received by the collector, eg. if there is a kafka in-between. That in turns allows to do maintenance on the collector, without messing up the statistics
> Allow using fields of the netflow packet to set the flow TimeReceived

- inlet/flow/decoder/netflow/decode.go
Look at IPFIX octets field for ColumnBytes.
See https://github.com/akvorado/akvorado/issues/1156.
> Statistics support for Cisco ASA/NSEL NATing

- common/clickhousedb/root.go
By defaut, the clickhouse-client does only failover (ConnOpenInOrder) the first instance that replies is used.
This enabled round-robin so that servers can all be used in parallel.
> Enable load-balancing for clickhouse

- console/data/docs/99-changelog.md
- console/line.go
- console/widgets.go
- orchestrator/clickhouse/version.go
- orchestrator/clickhouse/version_test.go
I don't want to keep disabling the experimental analyzer forever. The version check could be turned into disabling the experimental analyzer, but this is better to push people to update their versions.
To be pushed only when 24.3 (LTS) and 24.4 gets the fix.
> orchestrator/clickhouse: add compatibility check for INTERPOLATE issue

- console/line.go
- console/query.go
- console/sankey.go
- console/sankey_test.go
We noticed that we had inconsistencies on the TOPN pps query between the returned top IPs,
and we found that the sort was always using the Bytes instead of using the unit we have on the graph.
When we have a DOS for example, the packets are small, so the background noise in bytes is hiding the IP of interest in PPS.
I added a function to select the appropriate column based on the unit selected by the user.
> Use unit for sorting topX instead of always using bytes

- inlet/metadata/provider/gnmi/collector.go
Currently, for discovering interfaces' name, description and speed, the gNMI metadata provider assumes that all entries returned by the device always contain a single key.
However, this is not always the case. For example, on Nokia SR OS, sampling is enabled on logical interfaces that are defined inside router instances or VPRN services, rather than physical ports.
To give an example:
```
$ gnmic get -u akvorado ... \
--path 'state/service/vprn/interface/system-if-index'
[
{
...
"updates": [
{
"Path": "state/service/vprn[service-name=WAN_VRF]/interface[interface-name=primary_transit]/system-if-index",
"values": {
"state/service/vprn/interface/system-if-index": 264
}
},
...
```
Adding this path to if-index-paths, with interface-name as a if-name-keys, would not allow primary_transit to be …
> inlet/metadata: handle multiple keys in gNMI events

- docker/grafana/grafana.ini
Needs to be in section [users] instead of [security]
see:
https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#viewers_can_edit
> move viewers_can_edit to users section in grafana.ini

- orchestrator/clickhouse/migrations.go
Depending on (I guess) database configuration,
it is required to specify the full dict name (include database), or else we get "BAD_ARGUMENTS" error.
It seems like a good idea to always send the full table/dict name regardless, because it makes sure there is no conflict in case of duplicate table names (eg. multiple akvorados running on the same clickhous cluster).
> Fix system reload request to include db name

- console/config.go
- console/data/docs/03-usage.md
- console/frontend/src/components/InputDimensions.vue
- console/graph.go
- console/line.go
This is a quick followup on my previous PR #1635, which added the `Last` column to the DataTable.
This PR aims to make the DataTable also sortable by the `Last` column, like it is already possible with `Max`and `Avg`.
> feat/console: option to sort by last column

- inlet/routing/provider/bmp/rib.go
- inlet/routing/provider/bmp/rib_test.go
- inlet/routing/provider/bmp/tests.go
- inlet/routing/root_test.go
We noticed invalid DstNetMask and SrcNetMask values from routers with only a default route, where the value from flows is zero and replaced with information from the BMP provider.
We were able to confirm that the correct routes were advertised via BMP, and further discovered that the `plen` set in [`inlet/routing/provider/bmp/events.go` line 397](https://github.com/akvorado/akvorado/blob/98922dda9ff05d6d4b4c30781393250c2b353296/inlet/routing/provider/bmp/events.go#L397) did not always match the value when read in [`addPrefix()`](https://github.com/akvorado/akvorado/blob/98922dda9ff05d6d4b4c30781393250c2b353296/inlet/routing/provider/bmp/rib.go#L139).
We believe the cause might be that the `plen` attribute in is not considered in the `Equals()` and `Hash()` functions for the …
> routing: include routeAttributes.plen in .Equal() and .Hash()

- console/data/docs/02-configuration.md
- inlet/metadata/provider/gnmi/root.go
- inlet/metadata/provider/gnmi/srlinux_test.go
- inlet/metadata/provider/root.go
- inlet/metadata/provider/snmp/poller_test.go
- inlet/metadata/provider/snmp/root.go
- inlet/metadata/provider/static/config.go
- inlet/metadata/provider/static/config_test.go
- inlet/metadata/provider/static/root.go
- inlet/metadata/provider/static/root_test.go
- inlet/metadata/provider/static/source_test.go
- inlet/metadata/root.go
- inlet/metadata/root_test.go
- inlet/metadata/tests.go
As briefly discussed in https://github.com/akvorado/akvorado/discussions/1572 we've implemented a PR for processing only the configured interfaces in the static metadata provider and skip to the next provider for the rest. This behaviour can be enabled per exporter by setting `skip_missing_interfaces` to `true` in the static metadata provider configuration.
For this the `Provider` interface's `Query()` function is updated to use a pointer to the `query` parameter, so that the `ifIndexes` attribute can be updated. The static provider removes interfaces from this slice as it processes them, and returns `ErrSkipProvider` if interfaces were skipped.
> static metadata provider: add option skip missing interfaces

- console/data/docs/99-changelog.md
- docker/docker-compose-dev.yml
- docker/docker-compose.yml
- docker/versions.yml
Bitnami only maintain the latest version available (which may not be the LTS one) since a few months. See their [announcement](https://community.broadcom.com/tanzu/blogs/carlos-rodriguez-hernandez/2025/01/14/announcing-general-availability-of-bitnami-premium). Moreover, their images now have pull limits.
The main issue when migrating away is volumes. The replacement images may not use the same layout. Docker got the recent ability to use subvolumes.
For Zookeeper, we will remove its use at some point, so it does not matter. Kafka needs to be investigated more.
> Remove Bitnami images

- common/helpers/tls.go
- common/kafka/config.go
- common/kafka/config_test.go
- common/kafka/oauth.go
- common/kafka/oauth_test.go
- console/data/docs/02-configuration.md
- console/data/docs/99-changelog.md
- docker/docker-compose-dev.yml
- docker/versions.yml
The support is still pretty basic. Notably, scopes are not
configurable (waiting for someone to request them) and maybe there
client ID and secrets should not be provided as username/password.
Fix #1714
> common/kafka: add support for OAuth2

- docker/docker-compose.yml
Wait for kafka to be healthy to start akvorado-orchestrator to avoid a crash loop and service unhealthy when kafka takes too long to start.
> Add depends_on: kafka to avoid crash loop on startup

- cmd/orchestrator.go
- cmd/testdata/configurations/orchestrator-clickhousedb/expected.yaml
- cmd/testdata/configurations/orchestrator-clickhousedb/in.yaml
- common/clickhousedb/config.go
- common/clickhousedb/tests.go
- config/akvorado.yaml
- console/data/docs/02-configuration.md
- console/data/docs/99-changelog.md
- orchestrator/clickhouse/config.go
- orchestrator/clickhouse/migrations.go
- orchestrator/clickhouse/migrations_helpers.go
- orchestrator/clickhouse/migrations_test.go
- orchestrator/clickhouse/root.go
Instead, properly use them from the clickhousedb component. Also provide some automatic migration.
> orchestrator/clickhouse: do not embed clickhouse database settings

- .github/workflows/ci.yml
- Makefile
- cmd/version.go
- cmd/version_test.go
- console/data/docs/99-changelog.md
- docker/Dockerfile
- docker/Dockerfile.nix
This should be faster to build multiarch images, as Nix requires emulation, while we can build everything natively using builtin Go cross-compilation support. Moreover, caching should be better.
Also, add Nix build to CI.
Also, build more architectures (linux/arm/v7).
> docker: switch away from Nix to build Docker images

- outlet/kafka/functional_test.go
- outlet/kafka/metrics.go
- outlet/kafka/root.go
Monitoring consumer lag is useful to troubleshoot performance/scaling issues. It can currenctly be seen through kafka-ui, but a proper metric is more practical.
Unfortunately, JMX metrics on the broker don't expose this. It seems that people usually resort to monitoring from the consumer side, or through other external exporters like [Burrow](https://github.com/linkedin/Burrow) or [kafka_exporter](https://github.com/danielqsj/kafka_exporter).
franz-go/kadm provides a function to compute the consumer lag!
```
curl -s http://localhost:8080/api/v0/outlet/metrics | grep akvorado_outlet_kafka_consumergroup_lag_messages
```
This should return a somewhat stable and low number. The average value most likely depends on the configured ClickHouse batch size / max wait time, but monitoring for sudden …
> outlet/kafka: expose consumer lag as a prometheus metric

- console/filter.go
- console/filter_test.go
Hello
This PR adds autocomplete functionality for the ```SrcPort``` and ```DstPort``` filters. 
Example: if we enter ```SrcPort = http``` , it will display a list of all ports whose protocol name begins with ```http```.
This follows on from my first PR #1257
> console/filter: add autocomplete for the SrcPort and DstPort filters

- console/data/docs/99-changelog.md
- inlet/flow/input/udp/root.go
- inlet/flow/input/udp/socket.go
- inlet/flow/input/udp/socket_linux.go
- inlet/flow/input/udp/socket_others.go
- inlet/flow/input/udp/socket_test.go
If the kernel is too old for timestamping, it should not be fatal. I prefer to not accept SO_TIMESTAMP_OLD as the size of the timestamp is arch-dependent.
Fix #1978
> inlet/flow: make some of the socket options not fatal
